The detail book component is created
wolox-training/jlb-angular pull request #1
Opened 2020-09-29 21:00 UTC by Juliocho990

## Summary
- Completed the detailed texts of the book

## Screenshot
<img width="718" alt="book detail I" src="https://user-images.githubusercontent.com/17410581/94614685-30992b00-026c-11eb-8fa9-a70647299554.png">

## Trello Card
https://trello.com/c/wnY9YFTD/26-detalle-de-libro-i-textos

2020-09-29 23:45 UTC, eledwinn requested changes
Great job men. 👏 👏 👏

2020-09-29 23:45 UTC, eledwinn commented on .gitignore
> +.DS_Store
Please add empty lines at end of all files

2020-09-29 23:45 UTC, eledwinn commented on index.html
> +<!doctype html>
Use two spaces for indent all files

2020-09-29 23:45 UTC, eledwinn commented on index.html
> +</html>
Empty line at EOF :P

2020-09-29 23:45 UTC, eledwinn commented on scss/_colors.scss
> +$gray: #828282;
Same

2020-09-29 23:45 UTC, eledwinn commented on scss/detail.scss
> +		h1 {
Avoid to use element name selector in your CSS, we try using classes. Check our Style Guide here https://github.com/Wolox/tech-guides/blob/master/frontend/docs/css-style-guide.md

2020-09-29 23:45 UTC, eledwinn commented on scss/detail.scss
> +		margin: 0 0 36px 0;
Empty line between prop and selector please

2020-09-29 23:45 UTC, eledwinn commented on scss/detail.scss
> +			font-size: 22px;
If your `h2` and `span` tags have the same `font-size`, try set in same selector block.

2020-09-30 13:41 UTC, CrisVega08 requested changes

2020-09-30 13:41 UTC, CrisVega08 commented on scss/detail.scss
> +    margin: 0 0 52px 0;
margin-bottom: 52px;

2020-09-30 13:41 UTC, CrisVega08 commented on scss/detail.scss
> +  &__detail ul li{
avoid tag selectors

2020-09-30 13:41 UTC, CrisVega08 commented on scss/detail.scss
> +    margin: 0 0 36px 0;
margin-bottom: 36px;

2020-09-30 22:52 UTC, eledwinn approved these changes
Cool!!! 😎

2020-09-30 23:28 UTC, CrisVega08 approved these changes

2020-09-30 23:28 UTC, CrisVega08 commented on scss/detail.scss
> +  &__detail ul li{
```suggestion
  &__detail ul li {
```

2020-10-01 15:04 UTC, merged